---
title: "glmer"
author: "Tuan Nguyen"
date: "4/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries and Data
```{r}
library(readr)
library(lme4)
library(dplyr)
library(car)

# Reading in data
ecoDataReg <- read_csv("ecoDataReg.csv")

# Reference: https://stats.stackexchange.com/questions/13166/rs-lmer-cheat-sheet
```

## Normal Normal Hierarchical Model
```{r}
# Normal - Normal Hierarchy
normalNormal <- lmer(transFootprint ~ (1|continent) + 
                       log(population) + 
                       log(totalProduction) +
                       log(GDPperCapita) + 
                       totalGHG + log(HDI2015), 
                     data = ecoDataReg)
summary(normalNormal)
par(mfrow=c(1,1))
plot(normalNormal)

hist(ecoDataReg$transFootprint)
```

## Binomial - Normal Hierarchical Model
```{r}
# Binomial - Normal Hierarchy
binomialNormal <- glmer(binomFootprint ~ (1|continent) + 
                       population + 
                       totalProduction +
                       GDPperCapita + 
                       totalProduction + 
                       totalGHG + HDI2015, 
                     data = ecoDataReg)
summary(binomialNormal)
plot(binomialNormal)
```


## Tests
```{r}
test <- mutate_at(.vars = c("population", "GDPperCapita", 
                            "totalProduction", "totalGHG", "HDI2015"), 
                  .funs = funs( as.numeric(scale(.) )))
```

transFootprint tests
```{r}
# Model 1- Varying intercept
lmer1 <- lmer(log(netFootprint+15) ~ (1 + population|continent) + 
                (1 + totalProduction|continent) + 
                (1 + GDPperCapita|continent) + 
                (1 + HDI2015|continent) + population + 
                totalProduction + GDPperCapita + 
                HDI2015, data = ecoDataReg)

summary(lmer1)
plot(lmer1)
Anova(lmer1)

# Model 2
lmer2 <- lmer(log(netFootprint+15) ~ (1|continent) + 
                totalProduction + 
                (0 + totalProduction|continent) + 
                population + 
                (0 + population|continent) + 
                GDPperCapita + 
                (0 + GDPperCapita|continent) + 
                HDI2015 + 
                (0 + HDI2015|continent), data = ecoDataReg)
summary(lmer2)
plot(lmer2)
Anova(lmer2)

anova(lmer1, lmer2)
```

binomFootprint tests
```{r}
glmer1 <- glmer(binomFootprint ~ (1 + population|continent) + 
                  (1 + totalProduction|continent) + 
                  (1 + GDPperCapita|continent) + 
                  (1 + HDI2015|continent) + 
                  population + totalProduction + 
                  GDPperCapita + 
                  HDI2015, 
                data = ecoDataReg, family = binomial(link = "logit"))  
summary(glmer1)
plot(glmer1)

glmer2 <- glmer(log(netFootprint+15) ~ (1 + population|continent) + 
                  (1 + totalProduction|continent) + 
                  (1 + GDPperCapita|continent) + 
                  (1 + HDI2015|continent) + 
                  population + 
                  totalProduction + 
                  GDPperCapita + 
                  HDI2015, 
                data = ecoDataReg, 
                family = gaussian(link = "identity"))  
summary(glmer2)
plot(glmer2)

```

