---
title: "Wrangling"
author: "Shirley Cheung"
date: "April 25, 2018"
output: html_document
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r, message = FALSE, warning = FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(fitdistrplus)
library(lme4)
library(tree)
```

## Wrangling
+ biocapcity data is 2016
+ regional data is 2013
+ greenhouse data is 2013

### Eco / Biocapacity Data
```{r}
# Reading in eco dataset
ecoData <- read_csv("countries.csv") 
names(ecoData ) <- gsub(" ", "", names(ecoData )) 

# Cleaning up eco dataset
ecoData  <- ecoData  %>%
  rename("country" = "Country", 
         "region" = "Region",
         "population" = "Population(millions)",
         "totalFootprint" = "TotalEcologicalFootprint",
         "totalBiocap" = "TotalBiocapacity",
         "netFootprint" = "BiocapacityDeficitorReserve") %>%
  dplyr::select(country, region, population, GDPperCapita, netFootprint) %>%
  mutate(GDPperCapita = 
           str_replace_all(GDPperCapita, 
                           c("[:punct:]" = "", "\\$" = ""))) %>%
  mutate(GDPperCapita = as.numeric(GDPperCapita))

# Finding duplicates
table(ecoData$country)

# Removing duplicates
## Kept the observation with more data / entries that made more sense
ecoData <- ecoData %>%
  filter(!(country %in% c("Korea, Democratic People's Republic of",
                      "Congo", "Guinea")))
```

### Production Data
+ Adds total food production by country in 2013
```{r}
# Reading in regional data
## Final regional dataset is total food production by country in 2013
production <- read_csv("regional.csv") %>%
  replace_na(list(region = "NA")) %>%
  group_by(Area, Year) %>%
  mutate(totalProduction = as.numeric(sum(Production))) %>%
  filter(Year == 2013) %>%
  ungroup() %>%
  distinct(Area, .keep_all = TRUE) %>%
  dplyr::select('Area Abbreviation', Area, region, totalProduction)

# Finding countries in common that won't join because of spelling
spellingErrors <- anti_join(ecoData, production, by = c("country" = "Area")) 

# Fixing names and merging with production data
ecoData <- ecoData %>%
  mutate(country = recode(country, 
                          "Antigua and Barbuda" = "Antigua",
                          "Brunei Darussalam" = "Brunei",
                          "Cabo Verde" = "Cape Verde",
                          "Congo" = "Democratic Republic of the Congo",
                          "Congo, Democratic Republic of" =
                            "Democratic Republic of the Congo",
                          "Côte d'Ivoire" = "Ivory Coast",
                          "Iran, Islamic Republic of" = "Iran",
                          "Korea, Republic of" = "South Korea",
                          "Lao People's Democratic Republic" = "Laos",
                          "Libyan Arab Jamahiriya" = "Libya",
                          "Macedonia TFYR" = "Macedonia",
                          "Russian Federation" = "Russia",
                          "Saint Kitts and Nevis" = "Saint Kitts",
                          "Saint Vincent and Grenadines" = "Saint Vincent",
                          "Syrian Arab Republic" = "Syria",
                          "Tanzania, United Republic of" = "Tanzania",
                          "Trinidad and Tobago" = "Trinidad",
                          "United Kingdom" = "UK",
                          "United States of America" = "USA",
                          "Venezuela, Bolivarian Republic of" = "Venezuela",
                          "Viet Nam" = "Vietnam")) %>%
  left_join(production, by = c("country" = "Area")) %>%
  dplyr::select(-region.x) %>%
  rename("continent" = "region.y")
```

### Greenhouse Data
+ 2012 Greenhouse Data
```{r}
# Reading in greenhouse gas dataset
greenhouse <- read_csv("CAITGHGData.csv") %>%
  filter(Year == 2012) %>%
  rename("totalGHG" = `Total GHG Emissions Including Land-Use Change and Forestry (MtCO?e?)`) %>%
  dplyr::select(Country, totalGHG)
  
# Finding countries in common that won't join because of spelling
spellingErrors <- anti_join(greenhouse, ecoData, 
                            by = c("Country" = "country"))

# Fixing names
greenhouse <- greenhouse %>%
  mutate(Country = recode(Country,
                          "Antigua & Barbuda" = "Antigua",
                          "Bahamas, The" = "Bahamas",
                          "Bosnia & Herzegovina" = "Bosnia and Herzegovina",
                          "Congo, Dem. Rep." = 
                            "Democratic Republic of the Congo",
                          "Cote d'Ivoire" = "Ivory Coast",
                          "Korea, Rep. (South)" = "South Korea",
                          "Korea, Dem. Rep. (North)" = "North Korea",
                          "Macedonia, FYR" = "Macedonia",
                          "Russian Federation" = "Russia",
                          "Saint Kitts & Nevis" = "Saint Kitts",
                          "Saint Vincent & Grenadines" = "Saint Vincent",
                          "Trinidad & Tobago" = "Trinidad",
                          "United Kingdom" = "UK",
                          "United States of America" = "USA"))

# Merging greenhouse gas dataset with eco dataset
ecoData <- ecoData %>%
  left_join(greenhouse, by = c("country" = "Country"))
```

### Human Development Index Data
```{r}
# Reading in HDI data
HDI <- read_csv("HDI.csv")

# Finding countries in common that won't join because of spelling
spellingErrors <- anti_join(ecoData, HDI, by = c("country" = "Country"))

# Fixing spelling errors
HDI <- HDI %>%
  dplyr::select(Country, `2015`) %>%
  mutate(Country = recode(Country,
         "Antigua and Barbuda" = "Antigua", 
         "Bolivia (Plurinational State of)" = "Bolivia",
         "Brunei Darussalam" = "Brunei", 
         "Cabo Verde" = "Cape Verde",
         "Iran (Islamic Republic of)" = "Iran",
         "Lao People's Democratic Republic" = "Laos",
         "Libyan Arab Jamahiriya" = "Libya",
         "Russian Federation" = "Russia",
         "Saint Kitts and Nevis" = "Saint Kitts", 
         "Saint Vincent and the Grenadines" = "Saint Vincent", 
         "Viet Nam" = "Vietnam",
         "United Kingdom" = "UK",
         "United States" = "USA",
         "Venezuela (Bolivarian Republic of)" = "Venezuela",
         "Trinidad and Tobago" = "Trinidad",
         "Tanzania (United Republic of)" = "Tanzania",
         "Congo (Democratic Republic of the)" = 
           "Democratic Republic of the Congo",
         "The former Yugoslav Republic of Macedonia" = "Macedonia", 
         "Korea (Republic of)" = "South Korea",
         "Syrian Arab Republic" = "Syria")) %>%
  rename("HDI2015" = `2015`)
HDI$Country[HDI$HDI2015 == 0.474] <- "Ivory Coast"

# Merging with HDI data
ecoData <- ecoData %>%
  left_join(HDI, by = c("country" = "Country")) %>%
  drop_na() %>%
  mutate(binomFootprint = ifelse(netFootprint < 0, 0, 1)) %>%
  mutate(transFootprint = log(netFootprint + 15))

# Saving our final ecoData
write_csv(ecoData, "ecoData.csv")
```

## Regression 
```{r}
#normalizing the data
ecoData <- ecoData %>% 
  mutate(GDPperCapita = as.numeric(GDPperCapita)) %>%
  mutate_at(.vars = vars(population, totalProduction, GDPperCapita, `2015`), .funs = scale)
#Reference: https://stats.stackexchange.com/questions/13166/rs-lmer-cheat-sheet

# We are using these two models? Right now my simple understanding is that 
# V1 ~ (1|V2) + V3 + (0+V3|V2)

# V1 ~ (1+V3|V2) + V3

#first model is varying intercept
mixed.lmer <- lmer(log(netFootprint+15) ~ (1 + population|region) + (1 + totalProduction|region) + population + totalProduction, data = ecoData)
summary(mixed.lmer)
plot(mixed.lmer)


mixed.lmer2 <- lmer(log(netFootprint+15) ~ (1|region) + totalProduction + (0 + totalProduction|region) + population + (0 + population|region), data = ecoData)
summary(mixed.lmer2)
plot(mixed.lmer2)

# There are three kinds: varying intercept, varying slope, and both.
set.seed(42)
boston_idx = sample(1:nrow(Boston), nrow(Boston) / 2)
boston_trn = Boston[boston_idx,]
boston_tst = Boston[-boston_idx,]

# First we try regression trees

tree.model <- tree(log(netFootprint+15) ~ region + population + GDPperCapita + totalProduction, data=ecoData)
summary(tree.model)

plot(tree.model)
text(tree.model, cex=.75)

tree_model_cv = cv.tree(tree.model)
plot(tree_model_cv$size, sqrt(tree_model_cv$dev / nrow(ecoData)), type = "b",
     xlab = "Tree Size", ylab = "CV-RMSE")
```

## Fitting Distribution
```{r}
# Determining distribution of Y
# Our Y-variable = net biocapcity of each country
hist(log(ecoData$netFootprint))
descdist(log(ecoData$netFootprint + 15), discrete = FALSE)

# Looks like a beta distribution 
# Solve for parameters, alpha and beta, from the summary mu and sd
# Recall for the beta distribution
## mu = alpha / (alpha + beta)
## var = alpha*beta / [(alpha + beta)^2 (alpha + beta + 1)]
parameters <- function(mu, var) {
  alpha <- ((1 - mu)/var - 1/mu) * mu^2
  beta <- alpha * (1/mu - 1)
  return(params = list(alpha = alpha, beta = beta))
}
parameters(0.7020745, 11.77134^2)

# Problem: we have negative values for alpha, beta
# Also have negative values for our y's. Support of beta distribution
# should only be in (0,1). Need to do a transformation? Or not beta
# distribution. 

# fitBeta <- fitdist(countries$netBiocap, "beta")
# plot(fitBeta)

# Y = total biocapcity
hist(ecoData$totalBiocap)
descdist(ecoData$totalBiocap, discrete = FALSE)

# Y = total footprint
hist(ecoData$totalFootprint)
descdist(ecoData$totalFootprint, discrete = FALSE)
```

## Visualizations
```{r}
# Can you recycle code from project 3 and make another chloropleth map
# of the entire world where countries are filled in with their net 
# bio capacity? can test continuous case and then also categorical case where 
# we color by whether it's deficit or reserve
ggplot(aes(population, netFootprint), data = ecoData) + 
  geom_point() + 
  facet_wrap(~ continent) + 
  xlab("length") + 
  ylab("test score")
```


